/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.emp.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(value = "apiTest", description = "the apiTest API")
public interface ApiTestApi {

    default ApiTestApiDelegate getDelegate() {
        return new ApiTestApiDelegate() {};
    }

    /**
     * GET /apiTest : simple swagger test api
     * simple swagger test api
     *
     * @return Success (status code 200)
     *         or fail (status code 400)
     */
    @ApiOperation(value = "simple swagger test api", nickname = "apiTestGet", notes = "simple swagger test api", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = String.class),
        @ApiResponse(code = 400, message = "fail", response = String.class) })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/apiTest",
        produces = { "application/json" }
    )
    default ResponseEntity<String> apiTestGet() {
        return getDelegate().apiTestGet();
    }

}
