openapi: 3.0.3
info:
  description: Title
  title: Title
  version: 1.0.0
servers:
- url: https
paths:
  /CLibrary:
    get:
      operationId: getCLibrary
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCLibraryDto'
          description: 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
          description: 실패
      summary: Get Single Common Library
      x-accepts: application/json
    post:
      operationId: postCLibrary
      responses:
        "200":
          description: 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
          description: 실패
      summary: Save, Update Single Common Library
      x-accepts: application/json
components:
  schemas:
    GetCLibraryDto:
      example:
        name: actuator
      properties:
        name:
          example: actuator
          type: string
      type: object
    ErrorResponseDto:
      properties:
        errorCode:
          example: 00_0000_00
          type: string
        errorMessage:
          example: Error Invoke!
          type: string
      type: object

