openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'EMP Project'
  description: 'Gradle Library CRUD'
servers:
  - url: http://localhost:8080

paths:
  /apiTest:
    get:
      summary: simple swagger test api
      description: simple swagger test api
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: string
                example: responseTest
        400:
          description: fail
          content:
            application/json:
              schema:
                type: string
                example: responseTest

components:
  schemas:
    ErrorResponseDto:
      type: object
      properties:
        code:
          type: string
        message:
          type: string